spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:superhero;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
