DROP TABLE IF EXISTS SUPERHERO;

CREATE TABLE SUPERHERO (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255)
);

INSERT INTO SUPERHERO (name) VALUES ('Spiderman');
INSERT INTO SUPERHERO (name) VALUES ('Batman');
INSERT INTO SUPERHERO (name) VALUES ('All-Might');
INSERT INTO SUPERHERO (name) VALUES ('Wolverine');